// Code generated by smithy-kotlin-codegen. DO NOT EDIT!

package aws.sdk.kotlin.services.ec2.model



/**
 * Describes an additional detail for a path analysis.
 */
class AdditionalDetail private constructor(builder: Builder) {
    /**
     * The information type.
     */
    val additionalDetailType: kotlin.String? = builder.additionalDetailType
    /**
     * The path component.
     */
    val component: aws.sdk.kotlin.services.ec2.model.AnalysisComponent? = builder.component

    companion object {
        operator fun invoke(block: Builder.() -> kotlin.Unit): aws.sdk.kotlin.services.ec2.model.AdditionalDetail = Builder().apply(block).build()
    }

    override fun toString(): kotlin.String = buildString {
        append("AdditionalDetail(")
        append("additionalDetailType=$additionalDetailType,")
        append("component=$component)")
    }

    override fun hashCode(): kotlin.Int {
        var result = additionalDetailType?.hashCode() ?: 0
        result = 31 * result + (component?.hashCode() ?: 0)
        return result
    }

    override fun equals(other: kotlin.Any?): kotlin.Boolean {
        if (this === other) return true
        if (other == null || this::class != other::class) return false

        other as AdditionalDetail

        if (additionalDetailType != other.additionalDetailType) return false
        if (component != other.component) return false

        return true
    }

    inline fun copy(block: Builder.() -> kotlin.Unit = {}): aws.sdk.kotlin.services.ec2.model.AdditionalDetail = Builder(this).apply(block).build()

    class Builder {
        /**
         * The information type.
         */
        var additionalDetailType: kotlin.String? = null
        /**
         * The path component.
         */
        var component: aws.sdk.kotlin.services.ec2.model.AnalysisComponent? = null

        internal constructor()
        @PublishedApi
        internal constructor(x: aws.sdk.kotlin.services.ec2.model.AdditionalDetail) : this() {
            this.additionalDetailType = x.additionalDetailType
            this.component = x.component
        }

        @PublishedApi
        internal fun build(): aws.sdk.kotlin.services.ec2.model.AdditionalDetail = AdditionalDetail(this)

        /**
         * construct an [aws.sdk.kotlin.services.ec2.model.AnalysisComponent] inside the given [block]
         */
        fun component(block: aws.sdk.kotlin.services.ec2.model.AnalysisComponent.Builder.() -> kotlin.Unit) {
            this.component = aws.sdk.kotlin.services.ec2.model.AnalysisComponent.invoke(block)
        }
    }
}
