// Code generated by smithy-kotlin-codegen. DO NOT EDIT!

package aws.sdk.kotlin.services.ec2.model



/**
 * Describes the DNS options for an endpoint.
 */
class DnsOptionsSpecification private constructor(builder: Builder) {
    /**
     * The DNS records created for the endpoint.
     */
    val dnsRecordIpType: aws.sdk.kotlin.services.ec2.model.DnsRecordIpType? = builder.dnsRecordIpType

    companion object {
        operator fun invoke(block: Builder.() -> kotlin.Unit): aws.sdk.kotlin.services.ec2.model.DnsOptionsSpecification = Builder().apply(block).build()
    }

    override fun toString(): kotlin.String = buildString {
        append("DnsOptionsSpecification(")
        append("dnsRecordIpType=$dnsRecordIpType)")
    }

    override fun hashCode(): kotlin.Int {
        var result = dnsRecordIpType?.hashCode() ?: 0
        return result
    }

    override fun equals(other: kotlin.Any?): kotlin.Boolean {
        if (this === other) return true
        if (other == null || this::class != other::class) return false

        other as DnsOptionsSpecification

        if (dnsRecordIpType != other.dnsRecordIpType) return false

        return true
    }

    inline fun copy(block: Builder.() -> kotlin.Unit = {}): aws.sdk.kotlin.services.ec2.model.DnsOptionsSpecification = Builder(this).apply(block).build()

    class Builder {
        /**
         * The DNS records created for the endpoint.
         */
        var dnsRecordIpType: aws.sdk.kotlin.services.ec2.model.DnsRecordIpType? = null

        internal constructor()
        @PublishedApi
        internal constructor(x: aws.sdk.kotlin.services.ec2.model.DnsOptionsSpecification) : this() {
            this.dnsRecordIpType = x.dnsRecordIpType
        }

        @PublishedApi
        internal fun build(): aws.sdk.kotlin.services.ec2.model.DnsOptionsSpecification = DnsOptionsSpecification(this)
    }
}
