// Code generated by smithy-kotlin-codegen. DO NOT EDIT!

package aws.sdk.kotlin.services.ec2.model



class GetInstanceUefiDataResponse private constructor(builder: Builder) {
    /**
     * The ID of the instance from which to retrieve the UEFI data.
     */
    val instanceId: kotlin.String? = builder.instanceId
    /**
     * Base64 representation of the non-volatile UEFI variable store.
     */
    val uefiData: kotlin.String? = builder.uefiData

    companion object {
        operator fun invoke(block: Builder.() -> kotlin.Unit): aws.sdk.kotlin.services.ec2.model.GetInstanceUefiDataResponse = Builder().apply(block).build()
    }

    override fun toString(): kotlin.String = buildString {
        append("GetInstanceUefiDataResponse(")
        append("instanceId=$instanceId,")
        append("uefiData=$uefiData)")
    }

    override fun hashCode(): kotlin.Int {
        var result = instanceId?.hashCode() ?: 0
        result = 31 * result + (uefiData?.hashCode() ?: 0)
        return result
    }

    override fun equals(other: kotlin.Any?): kotlin.Boolean {
        if (this === other) return true
        if (other == null || this::class != other::class) return false

        other as GetInstanceUefiDataResponse

        if (instanceId != other.instanceId) return false
        if (uefiData != other.uefiData) return false

        return true
    }

    inline fun copy(block: Builder.() -> kotlin.Unit = {}): aws.sdk.kotlin.services.ec2.model.GetInstanceUefiDataResponse = Builder(this).apply(block).build()

    class Builder {
        /**
         * The ID of the instance from which to retrieve the UEFI data.
         */
        var instanceId: kotlin.String? = null
        /**
         * Base64 representation of the non-volatile UEFI variable store.
         */
        var uefiData: kotlin.String? = null

        internal constructor()
        @PublishedApi
        internal constructor(x: aws.sdk.kotlin.services.ec2.model.GetInstanceUefiDataResponse) : this() {
            this.instanceId = x.instanceId
            this.uefiData = x.uefiData
        }

        @PublishedApi
        internal fun build(): aws.sdk.kotlin.services.ec2.model.GetInstanceUefiDataResponse = GetInstanceUefiDataResponse(this)
    }
}
