// Code generated by smithy-kotlin-codegen. DO NOT EDIT!

package aws.sdk.kotlin.services.ec2.model



/**
 * The maintenance options of your instance.
 */
class LaunchTemplateInstanceMaintenanceOptions private constructor(builder: Builder) {
    /**
     * Disables the automatic recovery behavior of your instance or sets it to default.
     */
    val autoRecovery: aws.sdk.kotlin.services.ec2.model.LaunchTemplateAutoRecoveryState? = builder.autoRecovery

    companion object {
        operator fun invoke(block: Builder.() -> kotlin.Unit): aws.sdk.kotlin.services.ec2.model.LaunchTemplateInstanceMaintenanceOptions = Builder().apply(block).build()
    }

    override fun toString(): kotlin.String = buildString {
        append("LaunchTemplateInstanceMaintenanceOptions(")
        append("autoRecovery=$autoRecovery)")
    }

    override fun hashCode(): kotlin.Int {
        var result = autoRecovery?.hashCode() ?: 0
        return result
    }

    override fun equals(other: kotlin.Any?): kotlin.Boolean {
        if (this === other) return true
        if (other == null || this::class != other::class) return false

        other as LaunchTemplateInstanceMaintenanceOptions

        if (autoRecovery != other.autoRecovery) return false

        return true
    }

    inline fun copy(block: Builder.() -> kotlin.Unit = {}): aws.sdk.kotlin.services.ec2.model.LaunchTemplateInstanceMaintenanceOptions = Builder(this).apply(block).build()

    class Builder {
        /**
         * Disables the automatic recovery behavior of your instance or sets it to default.
         */
        var autoRecovery: aws.sdk.kotlin.services.ec2.model.LaunchTemplateAutoRecoveryState? = null

        internal constructor()
        @PublishedApi
        internal constructor(x: aws.sdk.kotlin.services.ec2.model.LaunchTemplateInstanceMaintenanceOptions) : this() {
            this.autoRecovery = x.autoRecovery
        }

        @PublishedApi
        internal fun build(): aws.sdk.kotlin.services.ec2.model.LaunchTemplateInstanceMaintenanceOptions = LaunchTemplateInstanceMaintenanceOptions(this)
    }
}
