// Code generated by smithy-kotlin-codegen. DO NOT EDIT!

package aws.sdk.kotlin.services.ec2.model



/**
 * The maintenance options of your instance.
 */
class LaunchTemplateInstanceMaintenanceOptionsRequest private constructor(builder: Builder) {
    /**
     * Disables the automatic recovery behavior of your instance or sets it to default. For more information, see [Simplified automatic recovery](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-instance-recover.html#instance-configuration-recovery).
     */
    val autoRecovery: aws.sdk.kotlin.services.ec2.model.LaunchTemplateAutoRecoveryState? = builder.autoRecovery

    companion object {
        operator fun invoke(block: Builder.() -> kotlin.Unit): aws.sdk.kotlin.services.ec2.model.LaunchTemplateInstanceMaintenanceOptionsRequest = Builder().apply(block).build()
    }

    override fun toString(): kotlin.String = buildString {
        append("LaunchTemplateInstanceMaintenanceOptionsRequest(")
        append("autoRecovery=$autoRecovery)")
    }

    override fun hashCode(): kotlin.Int {
        var result = autoRecovery?.hashCode() ?: 0
        return result
    }

    override fun equals(other: kotlin.Any?): kotlin.Boolean {
        if (this === other) return true
        if (other == null || this::class != other::class) return false

        other as LaunchTemplateInstanceMaintenanceOptionsRequest

        if (autoRecovery != other.autoRecovery) return false

        return true
    }

    inline fun copy(block: Builder.() -> kotlin.Unit = {}): aws.sdk.kotlin.services.ec2.model.LaunchTemplateInstanceMaintenanceOptionsRequest = Builder(this).apply(block).build()

    class Builder {
        /**
         * Disables the automatic recovery behavior of your instance or sets it to default. For more information, see [Simplified automatic recovery](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-instance-recover.html#instance-configuration-recovery).
         */
        var autoRecovery: aws.sdk.kotlin.services.ec2.model.LaunchTemplateAutoRecoveryState? = null

        internal constructor()
        @PublishedApi
        internal constructor(x: aws.sdk.kotlin.services.ec2.model.LaunchTemplateInstanceMaintenanceOptionsRequest) : this() {
            this.autoRecovery = x.autoRecovery
        }

        @PublishedApi
        internal fun build(): aws.sdk.kotlin.services.ec2.model.LaunchTemplateInstanceMaintenanceOptionsRequest = LaunchTemplateInstanceMaintenanceOptionsRequest(this)
    }
}
