// Code generated by smithy-kotlin-codegen. DO NOT EDIT!

package aws.sdk.kotlin.services.ec2.model



class ModifyInstanceMaintenanceOptionsResponse private constructor(builder: Builder) {
    /**
     * Provides information on the current automatic recovery behavior of your instance.
     */
    val autoRecovery: aws.sdk.kotlin.services.ec2.model.InstanceAutoRecoveryState? = builder.autoRecovery
    /**
     * The ID of the instance.
     */
    val instanceId: kotlin.String? = builder.instanceId

    companion object {
        operator fun invoke(block: Builder.() -> kotlin.Unit): aws.sdk.kotlin.services.ec2.model.ModifyInstanceMaintenanceOptionsResponse = Builder().apply(block).build()
    }

    override fun toString(): kotlin.String = buildString {
        append("ModifyInstanceMaintenanceOptionsResponse(")
        append("autoRecovery=$autoRecovery,")
        append("instanceId=$instanceId)")
    }

    override fun hashCode(): kotlin.Int {
        var result = autoRecovery?.hashCode() ?: 0
        result = 31 * result + (instanceId?.hashCode() ?: 0)
        return result
    }

    override fun equals(other: kotlin.Any?): kotlin.Boolean {
        if (this === other) return true
        if (other == null || this::class != other::class) return false

        other as ModifyInstanceMaintenanceOptionsResponse

        if (autoRecovery != other.autoRecovery) return false
        if (instanceId != other.instanceId) return false

        return true
    }

    inline fun copy(block: Builder.() -> kotlin.Unit = {}): aws.sdk.kotlin.services.ec2.model.ModifyInstanceMaintenanceOptionsResponse = Builder(this).apply(block).build()

    class Builder {
        /**
         * Provides information on the current automatic recovery behavior of your instance.
         */
        var autoRecovery: aws.sdk.kotlin.services.ec2.model.InstanceAutoRecoveryState? = null
        /**
         * The ID of the instance.
         */
        var instanceId: kotlin.String? = null

        internal constructor()
        @PublishedApi
        internal constructor(x: aws.sdk.kotlin.services.ec2.model.ModifyInstanceMaintenanceOptionsResponse) : this() {
            this.autoRecovery = x.autoRecovery
            this.instanceId = x.instanceId
        }

        @PublishedApi
        internal fun build(): aws.sdk.kotlin.services.ec2.model.ModifyInstanceMaintenanceOptionsResponse = ModifyInstanceMaintenanceOptionsResponse(this)
    }
}
