// Code generated by smithy-kotlin-codegen. DO NOT EDIT!

package aws.sdk.kotlin.services.ec2.model

import kotlin.collections.List

sealed class TpmSupportValues {

    abstract val value: kotlin.String

    object V2_0 : aws.sdk.kotlin.services.ec2.model.TpmSupportValues() {
        override val value: kotlin.String = "v2.0"
        override fun toString(): kotlin.String = value
    }

    data class SdkUnknown(override val value: kotlin.String) : aws.sdk.kotlin.services.ec2.model.TpmSupportValues() {
        override fun toString(): kotlin.String = value
    }

    companion object {
        /**
         * Convert a raw value to one of the sealed variants or [SdkUnknown]
         */
        fun fromValue(str: kotlin.String): aws.sdk.kotlin.services.ec2.model.TpmSupportValues = when(str) {
            "v2.0" -> V2_0
            else -> SdkUnknown(str)
        }

        /**
         * Get a list of all possible variants
         */
        fun values(): kotlin.collections.List<aws.sdk.kotlin.services.ec2.model.TpmSupportValues> = listOf(
            V2_0
        )
    }
}
