// Code generated by smithy-kotlin-codegen. DO NOT EDIT!

package aws.sdk.kotlin.services.s3.model

import kotlin.collections.List

sealed class ObjectAttributes {

    abstract val value: kotlin.String

    object Checksum : aws.sdk.kotlin.services.s3.model.ObjectAttributes() {
        override val value: kotlin.String = "Checksum"
        override fun toString(): kotlin.String = value
    }

    object Etag : aws.sdk.kotlin.services.s3.model.ObjectAttributes() {
        override val value: kotlin.String = "ETag"
        override fun toString(): kotlin.String = value
    }

    object ObjectParts : aws.sdk.kotlin.services.s3.model.ObjectAttributes() {
        override val value: kotlin.String = "ObjectParts"
        override fun toString(): kotlin.String = value
    }

    object ObjectSize : aws.sdk.kotlin.services.s3.model.ObjectAttributes() {
        override val value: kotlin.String = "ObjectSize"
        override fun toString(): kotlin.String = value
    }

    object StorageClass : aws.sdk.kotlin.services.s3.model.ObjectAttributes() {
        override val value: kotlin.String = "StorageClass"
        override fun toString(): kotlin.String = value
    }

    data class SdkUnknown(override val value: kotlin.String) : aws.sdk.kotlin.services.s3.model.ObjectAttributes() {
        override fun toString(): kotlin.String = value
    }

    companion object {
        /**
         * Convert a raw value to one of the sealed variants or [SdkUnknown]
         */
        fun fromValue(str: kotlin.String): aws.sdk.kotlin.services.s3.model.ObjectAttributes = when(str) {
            "Checksum" -> Checksum
            "ETag" -> Etag
            "ObjectParts" -> ObjectParts
            "ObjectSize" -> ObjectSize
            "StorageClass" -> StorageClass
            else -> SdkUnknown(str)
        }

        /**
         * Get a list of all possible variants
         */
        fun values(): kotlin.collections.List<aws.sdk.kotlin.services.s3.model.ObjectAttributes> = listOf(
            Checksum,
            Etag,
            ObjectParts,
            ObjectSize,
            StorageClass
        )
    }
}
